config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:index, :show, :new, :create, :destroy] do
    resources :doses, only: :create
    resources :reviews, only: [:index, :new, :create]
  end
  resources :doses, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :delete_all
  has_many :reviews, dependent: :delete_all
  has_many :ingredients, through: :doses

  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, :cocktail_id, :ingredient_id, presence: true
  validates_uniqueness_of :cocktail_id, :scope => [:ingredient_id]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :content, :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @doses = Dose.where(cocktail_id: @cocktail)
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    @dose.save
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/index.html.erb
<div class="container">
  <div class="cards">
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
      Breakfast
    </div>

    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/lunch.jpg)">
      Lunch
    </div>

    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/dinner.jpg)">
      Dinner
    </div>
  </div>
</div>


<!--   <h1>Cocktails</h1>

  <div class="cards">
    <% @cocktails.each do |cocktail| %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2250&q=80)">
          <%= link_to cocktail.name, cocktail_path(cocktail) %>
        </div>
    <% end %>
  </div> -->

app/views/cocktails/new.html.erb
<div class="container">

  <h1>Create a new Cocktail</h1>

  <%= simple_form_for(@cocktail) do |f| %>

  <% if @cocktail.errors.any? %>
      <div class="errors-container">
        <ul>
          <% @cocktail.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <%= f.input :name %>
  <%= f.submit "Add Cocktail", class: "btn btn-primary" %>

  <% end %>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <h1><%= @cocktail.name %></h1>
  <% @doses.each do |dose| %>
      <li>
        <%= dose.ingredient.name.capitalize %> | <%= dose.description %> ||
        <%= link_to "Delete", dose_path(dose),
          method: :delete,
          data: { confirm: "Are you sure?" } %>
      </li>
    <% end %>
  <%= link_to 'Back', cocktails_path, class: 'btn btn-primary' %>

  <h1>Add some Ingredients</h1>

  <%= simple_form_for [@cocktail, @dose] do |f| %>

  <% if @dose.errors.any? %>
      <div class="errors-container">
        <ul>
          <% @dose.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <%= f.association :ingredient %>
  <%= f.input :description %>
  <%= f.submit "Add ingredient", class: "btn btn-danger" %>
  <% end %>
  <%= link_to 'Back', cocktail_path(@cocktail), class: 'btn btn-primary' %>


</div>

app/views/doses/new.html.erb
<div class="container">
  <h1>Add some Ingredients</h1>

  <%= simple_form_for [@cocktail, @dose] do |f| %>

  <% if @dose.errors.any? %>
      <div class="errors-container">
        <ul>
          <% @dose.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <%= f.association :ingredient %>
  <%= f.input :description %>
  <%= f.submit "Add ingredient", class: "btn btn-danger" %>
  <% end %>
  <%= link_to 'Back', cocktail_path(@cocktail), class: 'btn btn-primary' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <a class="navbar-brand" href="#">
        <i class="fas fa-cocktail"></i>
    </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown">
            <a class="btn btn-flat" href="#">Add cocktail</a>
            </div>
          </li>
        </ul>
      </div>
    </div>

    <%= yield %>
    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>

app/views/reviews/index.html.erb
<div class="container">
  <h1>Reviews</h1>
  <%= <% @reviews.each do |review| %>
  <h4>Rating: <%= review.rating %></h4>
  <p><%= review.content %></p>
  <% end %>

</div>

app/views/reviews/new.html.erb
<div class="container">

  <h1>Create a new Review</h1>

  <%= simple_form_for [@cocktail, @review] do |f| %>

  <% if @review.errors.any? %>
      <div class="errors-container">
        <ul>
          <% @review.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <%= f.input :description %>
  <%= f.input :rating %>
  <%= f.submit "Add review", class: "btn btn-primary" %>

  <% end %>
</div>

<!-- Add the 1-5 rating in form and also in the model
then do the controller create action-->